### ISSUE TITLE
Broken on TOS 5.03

### ISSUE THREAD

**Issue by minexew** [shawnanastasio/TempleShell#1]
I don't know if you're still interested in this project, but the program fails to run on current TOS because `MkDir` was renamed to `DirMk`.

**Comment by shawnanastasio** [comment]
Hi, thanks for the heads up. I'm currently on vacation but when I return I'll fix this. If you would like to submit a PR to fix it sooner that's fine too.

**Comment by drsn0w** [comment]
Have you made any progress on this issue? TempleOS is very important to my daily workflow, and your shell makes it a lot easier. However without directory support my workflow is severely interrupted.

**Comment by shawnanastasio** [comment]
Fixed
